# Generated by Django 5.1.4 on 2025-04-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='taglie',
        ),
        migrations.RemoveField(
            model_name='taglia',
            name='quantita',
        ),
        migrations.CreateModel(
            name='ProdottoTaglie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=0)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotto_taglie', to='e_commerce.prodotto')),
                ('taglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.taglia')),
            ],
        ),
    ]
