# Generated by Django 5.1.4 on 2025-04-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_prodotto_taglie_remove_taglia_quantita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='quantita',
        ),
    ]
