# Generated by Django 5.1.4 on 2025-04-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_remove_prodotto_quantita'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineprodotto',
            name='taglia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.taglia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='tipo',
            field=models.CharField(choices=[('bambino', 'bambino'), ('donna', 'donna'), ('uomo', 'uomo')], max_length=20),
        ),
    ]
