# Generated by Django 5.1.4 on 2025-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_alter_ordineprodotto_taglia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
