# Generated by Django 5.1.4 on 2025-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_alter_ordine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineprodotto',
            name='stato',
            field=models.BooleanField(default=False),
        ),
    ]
