# Generated by Django 5.1.4 on 2025-04-27 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_ordineprodotto_stato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='sconto',
        ),
        migrations.AddField(
            model_name='prodotto',
            name='conteggio_acquisti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordine',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
